In [3]:
print("hello")

hello


# Basics Array Creation

In [12]:
import numpy as np

In [16]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [26]:
a = [1,2,3.5,"string",4,5]
a

[1, 2, 3.5, 'string', 4, 5]

In [28]:
np.array(a)

array(['1', '2', '3.5', 'string', '4', '5'], dtype='<U32')

In [34]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [36]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Generation Function

In [39]:
arr=np.arange(1,11,1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr1=np.zeros(6)
arr1

array([0., 0., 0., 0., 0., 0.])

In [45]:
arr2=np.zeros((6,6))
arr2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [49]:
arr3=np.ones((3,4))
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
arr4=np.linspace(1,10,50)
arr4

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

# Random Generation Functio

In [72]:
arr5=np.random.rand(10)
arr5

array([0.17467845, 0.87564512, 0.31837311, 0.7704181 , 0.78839664,
       0.08187037, 0.14528212, 0.67779252, 0.72403487, 0.58607023])

In [86]:
arr6=np.random.randn(10)
arr6

array([-0.39202988, -0.98352569,  0.9007596 , -2.03987526,  0.59008713,
        0.14465886, -1.20500738,  1.10938289,  0.33457107,  2.42541411])

In [92]:
arr7=np.random.randint(1,10,10)
arr7

array([2, 3, 8, 5, 9, 7, 4, 5, 5, 6])

# Array Attributes

In [99]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
a.shape

(3, 3)

In [103]:
a.size

9

In [105]:
a.dtype

dtype('int32')

# Array Methods

In [109]:
a.min()

1

In [111]:
a.max()

9

In [113]:
a.sum()

45

In [121]:
np.sum(a,axis=0)

array([12, 15, 18])

In [123]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [125]:
a.mean()


5.0

In [131]:
a.std()

2.581988897471611

In [133]:
a.argmax()

8

In [135]:
a.argmin()

0

# Reshaping and resizing

In [140]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [142]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

 # Numpy indexing and slicing of vectors:-

In [162]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [166]:
arr[3]

14

In [168]:
arr[1:5:1]

array([12, 13, 14, 15])

In [170]:
arr[-1:5:-1]

array([20, 19, 18, 17])

In [178]:
arr[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

# Numpy indexing and slicing of matrix

In [184]:
arr= np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [186]:
arr[0]

array([1, 2, 3, 4, 5])

In [188]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [190]:
arr[0,0]

1

In [196]:
arr[5,4]

30

In [207]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [213]:
arr[4:6,3:5]

array([[24, 25],
       [29, 30]])

# Boolean indexing

In [216]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [224]:
bool_index= arr % 2 ==0
bool_index

array([ True,  True,  True,  True,  True])

In [226]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])

# Numpy operation 

In [240]:
a1= np.array([1,2,3,4,5])
a2= np.array([6,7,8,9,10])

In [242]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [244]:
a1-a2


array([-5, -5, -5, -5, -5])

In [246]:
a1*a2


array([ 6, 14, 24, 36, 50])

In [248]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [250]:
a1%a2

array([1, 2, 3, 4, 5])

In [252]:
a1//a2

array([0, 0, 0, 0, 0])

In [254]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

# broadcasting 

In [258]:
l=[10,20,30]

In [260]:
for i in l:
    print(i+10)

20
30
40


In [262]:
list=[10,20,30]
arr=np.array(list)

In [267]:
arr+10

array([20, 30, 40])

In [271]:
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [273]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

# Deep and shallow copy

In [329]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [331]:
slice= a[:5]
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [333]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [335]:
a[4:6]*10


array([50, 60])

In [337]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# Deep copy

In [340]:
a
b=a

In [342]:
b[0]=99

In [344]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [346]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# Shallow copy

In [358]:
asd=np.arange(1,21)
asd

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [360]:
asd
b=asd.copy()

In [362]:
b[0]= 99

In [364]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [366]:
asd

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# Metrix Operation

In [383]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [385]:
A

array([[1, 2],
       [3, 4]])

In [387]:
B

array([[5, 6],
       [7, 8]])

In [389]:
A*B

array([[ 5, 12],
       [21, 32]])

In [391]:
A @ B

array([[19, 22],
       [43, 50]])

In [393]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [395]:
A.T

array([[1, 3],
       [2, 4]])

# Advance Array maniplation

Stacking array

In [403]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [405]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [407]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [409]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

 Spliting array

In [420]:
c= np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [424]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [426]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

# Numpy Exersise

Valid Sudoku

In [444]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [446]:
s.sum()

405

In [461]:
b=np.sum(s,axis=1)
for i in b:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("For rows Sudoku is valid")

For rows Sudoku is valid


In [463]:
c=np.sum(s,axis=1)
for i in c:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("For colums Sudoku is valid")

For colums Sudoku is valid


In [471]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [527]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [529]:
#Get the shape of the matrix.

In [531]:
data.shape

(5, 3)

In [533]:
#Find the average age of students.

In [535]:
np.mean(data[:,0])

18.4

In [537]:
#Extract Math marks of all students.

In [538]:
 data[:,1]

array([85, 92, 76, 65, 90])

In [539]:
#Find the highest Science mark.

In [543]:
np.max(data[:,2])

95

In [545]:
#Get details of the student who scored more than 90 in Math.

In [547]:
data[data[:,1]>90]

array([[19, 92, 88]])

In [549]:
#Increase Math marks of all students by 5.

In [551]:
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [552]:
#Find how many students are younger than 19.

In [555]:
len(data[data [:,0]<19])

3

In [556]:
#Calculate the average marks in each subject (column-wise mean).

In [559]:
np.mean(data[:,1:], axis=0)

array([86.6, 83.2])

In [560]:
#Get data of students who scored at least 80 in both subjects.

In [563]:
data[(data[:,1]>=80) & (data[:,2]>=80)] 

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [565]:
#Replace all Science marks < 75 with 0.

In [567]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [569]:
data[:,2][data[:,2]<75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])